In [163]:
import pandas as pd
import numpy as np

In [349]:
#选取的数据为正常工况的数据
data = pd.read_csv("../data/燃气轮机.csv", encoding="gbk")
data.to_pickle("../data/燃气轮机.pkl")
data.head(5)

,Time,DWATT,CSGV,CTIM,TTXD1_1,TTXD1_2,TTXD1_3,TTXD1_4,TTXD1_5,TTXD1_6,...,TTXD1_19,TTXD1_20,TTXD1_21,TTXD1_22,TTXD1_23,TTXD1_24,TTXM,TTXSP1,TTXSP3,TTXSP2
0,#!Units,MW,na,deg F,deg F,deg F,deg F,deg F,deg F,deg F,...,deg F,deg F,deg F,naF,naF,naF,deg F,deg F,deg F,deg F
1,#!Description,Generator Watts Max Selected,IGV angle in deg,Compressor Inlet Temperature,Exhaust Thermocouple 1- Compensated,Exhaust Thermocouple 2- Compensated,Exhaust Thermocouple 3- Compensated,Exhaust Thermocouple 4- Compensated,Exhaust Thermocouple 5- Compensated,Exhaust Thermocouple 6 - Compensated,...,Exhaust Thermocouple 19 - Compensated,Exhaust Thermocouple 20 - Compensated,Exhaust Thermocouple 21 - Compensated,Exhaust Thermocouple 22 - Compensated,Exhaust Thermocouple 23 - Compensated,Exhaust Thermocouple 24 - Compensated,Exhaust Temp Median Corrected By Average,Combustion Monitor Actual Spread 1,Combustion Monitor Actual Spread 3,Combustion Monitor Actual Spread 2
2,2015/8/1 0:00,103.0826721,84.05797577,91.35520935,1056.271606,1056.249512,1056.90564,1039.57605,1051.324463,1071.620239,...,1040.360107,1044.769287,1061.994507,1052.054688,1055.862671,1061.955322,1055.949707,25.66916656,23.58292007,24.93045998
3,2015/8/1 1:00,103.3062134,84.06842041,89.63658905,1057.366943,1055.130981,1057.074707,1037.682373,1049.881348,1070.99231,...,1040.169312,1042.369751,1060.376343,1050.632324,1053.875122,1060.029053,1052.199707,25.02660942,22.51792336,23.52773857
4,2015/8/1 2:00,103.5618591,84.05568695,89.13874054,1055.688599,1053.412842,1056.954224,1039.199585,1050.531128,1071.470703,...,1040.676514,1041.763428,1062.228394,1050.305054,1056.360107,1059.859985,1054.869141,26.2706337,22.97101974,22.13184357

In [354]:
filter_data1 = data.iloc[3:-1, 1:].reset_index(drop=True).astype("float32")
filter_data1

,DWATT,CSGV,CTIM,TTXD1_1,TTXD1_2,TTXD1_3,TTXD1_4,TTXD1_5,TTXD1_6,TTXD1_7,...,TTXD1_19,TTXD1_20,TTXD1_21,TTXD1_22,TTXD1_23,TTXD1_24,TTXM,TTXSP1,TTXSP3,TTXSP2
0,103.306213,84.068420,89.636589,1057.366943,1055.130981,1057.074707,1037.682373,1049.881348,1070.992310,1050.537720,...,1040.169312,1042.369751,1060.376343,1050.632324,1053.875122,1060.029053,1052.199707,25.026609,22.517923,23.527739
1,103.561859,84.055687,89.138741,1055.688599,1053.412842,1056.954224,1039.199585,1050.531128,1071.470703,1051.274048,...,1040.676514,1041.763428,1062.228394,1050.305054,1056.360107,1059.859985,1054.869141,26.270634,22.971020,22.131844
2,103.544197,84.063721,88.771164,1056.649536,1054.690308,1058.509521,1037.749512,1047.575073,1069.485229,1049.310425,...,1039.704102,1042.206299,1060.811523,1051.064087,1054.896729,1059.316284,1053.093628,25.267162,22.159866,22.324282
3,77.352463,61.772305,97.532494,1093.326172,1090.555420,1087.083008,1088.796143,1083.110962,1088.895142,1079.944946,...,1085.520508,1087.992065,1087.710327,1075.902954,1095.732300,1092.937622,1088.570312,22.870007,17.258978,20.664642
4,99.559967,76.909355,89.048416,1062.718506,1064.148193,1063.577393,1048.179443,1061.395508,1071.485962,1057.560913,...,1043.226318,1055.401611,1074.675171,1063.646606,1065.093872,1071.851807,1063.424683,31.840464,23.657434,24.026197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3295,112.426826,77.213676,66.249962,1048.510986,1047.086426,1056.008423,1025.266968,1035.413208,1054.772339,1032.826416,...,1026.986694,1025.672729,1037.216187,1032.404541,1027.528076,1040.897339,1038.746948,35.194969,29.229548,29.998344
3296,112.704132,76.445351,64.849571,1048.572144,1048.710083,1054.297485,1026.583984,1037.595093,1055.229004,1031.724854,...,1026.992310,1024.554932,1037.584595,1031.122925,1028.291260,1043.208496,1038.613037,36.323429,29.302021,29.744034
3297,119.111237,84.038620,63.397781,1045.154785,1038.030396,1039.061157,1019.505493,1038.511230,1044.232544,1030.629761,...,1028.180542,1022.174011,1027.825806,1029.152954,1022.238098,1040.633057,1030.151001,33.367863,26.709309,27.973347
3298,118.151978,81.932114,62.170582,1041.951660,1038.348511,1035.922974,1018.770142,1035.812866,1044.086182,1031.420776,...,1021.176086,1016.641479,1026.359497,1023.648376,1019.497314,1036.906982,1028.427368,31.865753,24.463263,26.945084
3299,102.683014,65.452133,61.815758,1055.776611,1066.332153,1064.029419,1043.970093,1054.931641,1058.647095,1038.045898,...,1027.307983,1044.416992,1056.234619,1040.293335,1035.377441,1057.822021,1050.497559,36.973442,30.705767,34.654716

In [355]:
filter_data2 = data.iloc[3:-1, 0].reset_index(drop=True)
filter_data2

0         2015/8/1 1:00
1         2015/8/1 2:00
2         2015/8/1 3:00
3         2015/8/1 4:00
4         2015/8/1 5:00
             ...
3295    2016/3/31 19:00
3296    2016/3/31 20:00
3297    2016/3/31 21:00
3298    2016/3/31 22:00
3299    2016/3/31 23:00
Name: Time, Length: 3300, dtype: object

In [356]:
filter_data3 = pd.to_datetime(filter_data2)

In [357]:
data2 = pd.concat([filter_data1,filter_data3], axis=1)
data2

,DWATT,CSGV,CTIM,TTXD1_1,TTXD1_2,TTXD1_3,TTXD1_4,TTXD1_5,TTXD1_6,TTXD1_7,...,TTXD1_20,TTXD1_21,TTXD1_22,TTXD1_23,TTXD1_24,TTXM,TTXSP1,TTXSP3,TTXSP2,Time
0,103.306213,84.068420,89.636589,1057.366943,1055.130981,1057.074707,1037.682373,1049.881348,1070.992310,1050.537720,...,1042.369751,1060.376343,1050.632324,1053.875122,1060.029053,1052.199707,25.026609,22.517923,23.527739,2015-08-01 01:00:00
1,103.561859,84.055687,89.138741,1055.688599,1053.412842,1056.954224,1039.199585,1050.531128,1071.470703,1051.274048,...,1041.763428,1062.228394,1050.305054,1056.360107,1059.859985,1054.869141,26.270634,22.971020,22.131844,2015-08-01 02:00:00
2,103.544197,84.063721,88.771164,1056.649536,1054.690308,1058.509521,1037.749512,1047.575073,1069.485229,1049.310425,...,1042.206299,1060.811523,1051.064087,1054.896729,1059.316284,1053.093628,25.267162,22.159866,22.324282,2015-08-01 03:00:00
3,77.352463,61.772305,97.532494,1093.326172,1090.555420,1087.083008,1088.796143,1083.110962,1088.895142,1079.944946,...,1087.992065,1087.710327,1075.902954,1095.732300,1092.937622,1088.570312,22.870007,17.258978,20.664642,2015-08-01 04:00:00
4,99.559967,76.909355,89.048416,1062.718506,1064.148193,1063.577393,1048.179443,1061.395508,1071.485962,1057.560913,...,1055.401611,1074.675171,1063.646606,1065.093872,1071.851807,1063.424683,31.840464,23.657434,24.026197,2015-08-01 05:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3295,112.426826,77.213676,66.249962,1048.510986,1047.086426,1056.008423,1025.266968,1035.413208,1054.772339,1032.826416,...,1025.672729,1037.216187,1032.404541,1027.528076,1040.897339,1038.746948,35.194969,29.229548,29.998344,2016-03-31 19:00:00
3296,112.704132,76.445351,64.849571,1048.572144,1048.710083,1054.297485,1026.583984,1037.595093,1055.229004,1031.724854,...,1024.554932,1037.584595,1031.122925,1028.291260,1043.208496,1038.613037,36.323429,29.302021,29.744034,2016-03-31 20:00:00
3297,119.111237,84.038620,63.397781,1045.154785,1038.030396,1039.061157,1019.505493,1038.511230,1044.232544,1030.629761,...,1022.174011,1027.825806,1029.152954,1022.238098,1040.633057,1030.151001,33.367863,26.709309,27.973347,2016-03-31 21:00:00
3298,118.151978,81.932114,62.170582,1041.951660,1038.348511,1035.922974,1018.770142,1035.812866,1044.086182,1031.420776,...,1016.641479,1026.359497,1023.648376,1019.497314,1036.906982,1028.427368,31.865753,24.463263,26.945084,2016-03-31 22:00:00
3299,102.683014,65.452133,61.815758,1055.776611,1066.332153,1064.029419,1043.970093,1054.931641,1058.647095,1038.045898,...,1044.416992,1056.234619,1040.293335,1035.377441,1057.822021,1050.497559,36.973442,30.705767,34.654716,2016-03-31 23:00:00